### PR TITLE
chore: upgrade swc

### PR DESCRIPTION
**Pull request by JiangWeixian**

### CODE REVIEW

**Comment by hjkcai** [comment]
There is a additional file `rust-toolchain` declared to use nightly-2024-01-07 version of rust toolchain. Is latest stable version of rust toolchain acceptable? I guess it don't have to be specific nightly version.

**Comment by JiangWeixian** [comment]
Some crates need higher version of rust, should we just use same version defined  in https://github.com/swc-project/plugins/blob/main/rust-toolchain repo?

**Comment by hjkcai** [comment]
Sure. That will be good.

**Comment by hjkcai** [comment]
I have published version 0.3.0. BTW would you like to be a collaborator of this project?

**Comment by JiangWeixian** [comment]
> I have published version 0.3.0. BTW would you like to be a collaborator of this project?

Sure, i would be happy to do that

**Comment by hjkcai** [comment]
You are already the collaborator of this Github project. Feel free to commit directly to this repo.

I have invited [~qidanta](https://www.npmjs.com/~qidanta) to be a maintainer of this npm package. I'm sure that's you😏

**Pull request merged**
